import type { CityConfig } from '../types';

export const INDIAN_CITIES: CityConfig[] = [
  {
    id: 'delhi-ncr',
    name: 'Delhi NCR',
    state: 'Delhi / NCR',
    coordinates: [77.2090, 28.6139],
    zoom: 11,
    population: '32.9M',
    activeStations: 5,
    avgAqi: 242,
    status: 'active',
    dominantPollutant: 'PM2.5',
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    coordinates: [72.8777, 19.0760],
    zoom: 11,
    population: '21.3M',
    activeStations: 2,
    avgAqi: 156,
    status: 'active',
    dominantPollutant: 'PM10',
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    coordinates: [72.5714, 23.0225],
    zoom: 11,
    population: '8.6M',
    activeStations: 1,
    avgAqi: 178,
    status: 'active',
    dominantPollutant: 'PM2.5',
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    coordinates: [75.7873, 26.9124],
    zoom: 11,
    population: '4.2M',
    activeStations: 2,
    avgAqi: 188,
    status: 'active',
    dominantPollutant: 'PM10',
  },
  {
    id: 'lucknow',
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    coordinates: [80.9462, 26.8467],
    zoom: 11,
    population: '3.9M',
    activeStations: 1,
    avgAqi: 215,
    status: 'active',
    dominantPollutant: 'PM2.5',
  },
  {
    id: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    coordinates: [88.3639, 22.5726],
    zoom: 11,
    population: '15.3M',
    activeStations: 1,
    avgAqi: 164,
    status: 'active',
    dominantPollutant: 'PM2.5',
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    coordinates: [77.5946, 12.9716],
    zoom: 11,
    population: '13.6M',
    activeStations: 2,
    avgAqi: 92,
    status: 'active',
    dominantPollutant: 'NO2',
  },
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    coordinates: [78.4867, 17.3850],
    zoom: 11,
    population: '10.8M',
    activeStations: 1,
    avgAqi: 124,
    status: 'active',
    dominantPollutant: 'PM10',
  },
  {
    id: 'chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    coordinates: [80.2707, 13.0827],
    zoom: 11,
    population: '11.9M',
    activeStations: 2,
    avgAqi: 86,
    status: 'active',
    dominantPollutant: 'SO2',
  },
];

export const DEFAULT_CITY = INDIAN_CITIES[0]; // Delhi NCR

export function getCityById(id: string): CityConfig {
  return INDIAN_CITIES.find(c => c.id === id) || DEFAULT_CITY;
}
